// The demo film, as data: what is said, what is shown, and how long each beat holds.
//
// Narration is generated by Gemini TTS (narrate.mjs), the browser is driven by Playwright (record.mjs), and each
// beat is held for as long as its narration takes, so picture and voice stay in step without hand-tuning.
// The app runs with ?brand=generic so no client name appears on screen.

export const VIDEO = { width: 1920, height: 1080, base: "http://127.0.0.1:5188", pad: 700 };

/** A beat: narration text, the caption burned on screen, and what the browser does while it is spoken. */
export const BEATS = [
  {
    id: "title",
    card: { title: "CAFM for contractors", subtitle: "Built on Kissflow · Custom UI, real workflow, real data" },
    say: "This is a facilities management application for a construction contractor, built on Kissflow. Everything you are about to see runs on live Kissflow data.",
    hold: 1200
  },
  {
    id: "problem",
    card: { title: "The problem", subtitle: "A contractor's risk does not end at handover" },
    say: "When a building is handed over, the contractor still carries the defects for twelve months, and structural liability for ten years. Every resident complaint is quietly a financial question: is this ours to fix for free, or can we charge it back?",
    hold: 1000
  },
  {
    id: "resident-call",
    goto: "#/me/voice",
    role: "resident",
    caption: "A resident just talks. No app to learn, no form to fill.",
    say: "It starts with a resident. She does not open a form. She talks, in English or Arabic, and the assistant asks only what is missing.",
    action: "voice-start",
    hold: 2600
  },
  {
    id: "voice-card",
    caption: "The job card fills itself while she speaks",
    say: "As she speaks, the job card fills in: the problem, the room, since when, whether anyone at home struggles with the heat, and when a technician can come in.",
    action: "voice-continue",
    hold: 2600
  },
  {
    id: "voice-logged",
    caption: "Logged with the real reference, priority and liability",
    say: "She confirms, and the work order is created. The assistant reads back the reference the system generated. Note what the system decided on its own: priority two, because an air conditioning fault in summer is urgent, and the contractor is liable, because this building is still inside its defects period.",
    action: "voice-finish",
    hold: 2600
  },
  {
    id: "arabic",
    goto: "#/me/voice",
    lang: "ar",
    caption: "العربية · the whole app, right to left",
    say: "The same call works in Arabic. The entire application flips to right to left, including the voice agent.",
    action: "arabic-glance",
    hold: 2200
  },
  {
    id: "queue",
    goto: "#/queue",
    role: "fm_manager",
    lang: "en",
    caption: "Every job carries its own clock and its own liability",
    say: "In the work order list, every job already carries a priority, a liability and a running service level clock. Nobody typed those in.",
    hold: 2000
  },
  {
    id: "detail",
    goto: "#/wo/WO-04832",
    caption: "Who pays, decided at the moment the request arrives",
    say: "Open one and the decision is on the record: inside the defects period, the contractor is liable, and the job was routed to the subcontractor who did the original installation. Every step is timestamped underneath.",
    hold: 2600
  },
  {
    id: "technician",
    goto: "#/tech",
    role: "technician",
    caption: "The technician's phone: the same system",
    say: "The technician sees the job on a phone. Same system, no separate app: checklist, photographs, the true cause of the fault, and a signature.",
    action: "tech-open",
    hold: 2600
  },
  {
    id: "recovery",
    goto: "#/dlp",
    role: "dlp_manager",
    caption: "The cost charged back to the subcontractor who caused it",
    say: "When the cause is the installer's fault, the cost is charged back to them, with the photographs and the timestamps attached. That turns an argument into a claim that can be defended.",
    hold: 2600
  },
  {
    id: "batch",
    goto: "#/command",
    role: "executive",
    caption: "One batch, one subcontractor, one pattern",
    say: "The command centre watches for patterns. Here the same valve actuator has failed across one batch of units, all installed by the same subcontractor. That is a claim for the batch, not for one flat.",
    hold: 2600
  },
  {
    id: "assurance",
    goto: "#/compliance",
    role: "compliance",
    caption: "Certificates, evidence and the audit pack",
    say: "Compliance is on the same record: Civil Defence certificates, planned maintenance with evidence, and an audit pack generated on demand.",
    hold: 2200
  },
  {
    id: "report",
    goto: "#/reports",
    role: "fm_manager",
    caption: "The monthly client report writes itself",
    say: "And the monthly client report writes itself from the same work orders, so the numbers in the meeting are the numbers in the system.",
    hold: 2200
  },
  {
    id: "proof",
    goto: "#/admin/data",
    role: "admin",
    caption: "Real Kissflow records, not a mock-up",
    say: "None of this is a mock-up. Every record sits in Kissflow: forms, processes and boards, with the workflow, the permissions and the audit trail that come with it.",
    hold: 2400
  },
  {
    id: "end",
    card: { title: "Built on Kissflow", subtitle: "Custom UI · workflow · AI, on one platform" },
    say: "Custom interface, real workflow, and artificial intelligence where it earns its place. Built on Kissflow.",
    hold: 1600
  }
];
